import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { SpeedInsights } from '@vercel/speed-insights/next';
import AppProvider from '@/components/providers/app-provider';
import { getServerUser } from '@/lib/auth';
import { GlobalHeader } from '@/components/header/global-header';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getServerUser();
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppProvider user={user}>
          <div className="flex min-h-svh w-full flex-col justify-center">
            <GlobalHeader />
            <div className="scrollNone relative flex flex-1 flex-col gap-4 overflow-auto">
              <div className={'absolute h-full w-full p-4'}>{children}</div>
            </div>
          </div>
        </AppProvider>
        <SpeedInsights />
      </body>
    </html>
  );
}
