import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { SpeedInsights } from '@vercel/speed-insights/next';
import SystemProvider from '@/components/system-provider';
import Test from '@/app/components/test';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SystemProvider>
          <div className="flex min-h-svh w-full flex-col justify-center">
            <div className="scrollNone relative flex flex-1 flex-col gap-4 overflow-auto">
              <div className={'absolute h-full w-full p-4 pt-0'}>
                <Test />
                {children}
              </div>
            </div>
          </div>
        </SystemProvider>
        <SpeedInsights />
      </body>
    </html>
  );
}
